#%RAML 1.0

title: server-accounts
version: 1
baseUri: http://user.wargos.ninja:5000/
mediaType: application/json

/:
  post:
    description: Gets uptime and version.
    body:
    responses:
      200:
        body:
          application/json:
            schema:
              {
                "title":"sales-api",
                "uptime":"2016-11-14T01:05:06.974Z",
                "version":"20161007"
              }

/p1:
  /accounts:
    post:
      body:
        application/json:
          example: !include schema/user/user.post.json
      responses:
        200:
          body:
            application/json:
              example: !include schema/user/user.json
    get:
      responses:
        200:
          body:
            application/json:
              example: !include schema/user/user.array.json

    /{account_id}:
      get:
        responses:
          200:
            body:
              application/json:
                example: !include schema/user/user.json
      put:
        body:
          application/json:
            example: !include schema/user/user.post.json
        responses:
          200:
            body:
              application/json:
                example: !include schema/user/user.json
      delete:
        responses:
          205:
  /login:
    post:
      body:
        application/json:
          example: !include schema/login/data.json
      responses:
        200:
          body:
            application/json:
              example: !include schema/login/response.json
  /logout:
    post:
      responses:
        204:
  /credentials:    
    get:
      responses:
        200:
          body:
            application/json:
              example: !include schema/user/user.array.json

    /{credential_id}:
      get:
        responses:
          200:
            body:
              application/json:
                example: !include schema/account/v2/get.credential.json
      put:
        body:
          application/json:
            example: !include schema/account/credentials/credential.json
        responses:
          200:
            body:
              application/json:
                example: !include schema/account/v2/get.credential.json
      delete:
        responses:
          205:
/p2:
  /accounts:  
    /{accounts_id}:
      get:
        responses:
          200:
            body:
              application/json:
                example: !include schema/account/credentials/array.credentials.json
      /credentials:
        post:
          body:
            application/json:
              example: !include schema/account/credentials/credential.json
          responses:
            200:
              body:
                application/json:
                  example: !include schema/account/v2/get.credential.json